"""Initial migration

Revision ID: e477fc9e389e
Revises: 
Create Date: 2025-09-11 12:33:45.762438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e477fc9e389e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_fetch_logs_created_at', table_name='content_fetch_logs')
    op.drop_index('ix_content_fetch_logs_id', table_name='content_fetch_logs')
    op.drop_index('ix_content_fetch_logs_source_name', table_name='content_fetch_logs')
    op.drop_table('content_fetch_logs')
    op.drop_index('idx_content_published_quality', table_name='content')
    op.drop_index('idx_content_type_source', table_name='content')
    op.drop_index('ix_content_content_type', table_name='content')
    op.drop_index('ix_content_id', table_name='content')
    op.drop_index('ix_content_published_at', table_name='content')
    op.drop_index('ix_content_quality_score', table_name='content')
    op.drop_index('ix_content_source', table_name='content')
    op.drop_index('ix_content_source_id', table_name='content')
    op.drop_table('content')
    op.drop_index('IDX_session_expire', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_recommendation_score', table_name='recommendations')
    op.drop_index('idx_recommendation_user_shown', table_name='recommendations')
    op.drop_index('ix_recommendations_id', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('ix_user_profiles_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.alter_column('content_items', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('uq_content_items_normalized_url', table_name='content_items', postgresql_where='(normalized_url IS NOT NULL)')
    op.create_unique_constraint('uq_content_items_normalized_url', 'content_items', ['normalized_url'])
    op.create_index('idx_content_items_published', 'content_items', ['published_at'], unique=False)
    op.create_index('idx_content_items_type', 'content_items', ['type'], unique=False)
    op.create_index(op.f('ix_content_items_normalized_url'), 'content_items', ['normalized_url'], unique=False)
    op.create_index(op.f('ix_content_items_published_at'), 'content_items', ['published_at'], unique=False)
    op.create_index(op.f('ix_content_items_type'), 'content_items', ['type'], unique=False)
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.Text(), server_default='{}', nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'interests')
    op.drop_column('users', 'profile_image_url')
    op.drop_index(op.f('ix_content_items_type'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_published_at'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_normalized_url'), table_name='content_items')
    op.drop_index('idx_content_items_type', table_name='content_items')
    op.drop_index('idx_content_items_published', table_name='content_items')
    op.drop_constraint('uq_content_items_normalized_url', 'content_items', type_='unique')
    op.create_index('uq_content_items_normalized_url', 'content_items', ['normalized_url'], unique=False, postgresql_where='(normalized_url IS NOT NULL)')
    op.alter_column('content_items', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interests_explicit', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('interests_inferred', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('interest_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('content_type_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('topic_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('complexity_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('length_preference', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('active_hours', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('engagement_patterns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('discovery_vs_focus', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='user_profiles_user_id_key')
    )
    op.create_index('ix_user_profiles_id', 'user_profiles', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('algorithm_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('recommendation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('shown_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('interacted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name='recommendations_content_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recommendations_pkey')
    )
    op.create_index('ix_recommendations_id', 'recommendations', ['id'], unique=False)
    op.create_index('idx_recommendation_user_shown', 'recommendations', ['user_id', 'shown_at'], unique=False)
    op.create_index('idx_recommendation_score', 'recommendations', ['score'], unique=False)
    op.create_table('sessions',
    sa.Column('sid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sess', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('expire', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sid', name='sessions_pkey')
    )
    op.create_index('IDX_session_expire', 'sessions', ['expire'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('engagement_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='content_pkey')
    )
    op.create_index('ix_content_source_id', 'content', ['source_id'], unique=False)
    op.create_index('ix_content_source', 'content', ['source'], unique=False)
    op.create_index('ix_content_quality_score', 'content', ['quality_score'], unique=False)
    op.create_index('ix_content_published_at', 'content', ['published_at'], unique=False)
    op.create_index('ix_content_id', 'content', ['id'], unique=False)
    op.create_index('ix_content_content_type', 'content', ['content_type'], unique=False)
    op.create_index('idx_content_type_source', 'content', ['content_type', 'source'], unique=False)
    op.create_index('idx_content_published_quality', 'content', ['published_at', 'quality_score'], unique=False)
    op.create_table('content_fetch_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('items_fetched', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('items_new', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fetch_duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='content_fetch_logs_pkey')
    )
    op.create_index('ix_content_fetch_logs_source_name', 'content_fetch_logs', ['source_name'], unique=False)
    op.create_index('ix_content_fetch_logs_id', 'content_fetch_logs', ['id'], unique=False)
    op.create_index('ix_content_fetch_logs_created_at', 'content_fetch_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
